version: "3.1"

networks:
  local.net:

services:
  c_develop:
    container_name: dev.me
    hostname: dev.me
    image: dev:1.0
    build:
      context: ./dev
    environment:
    - TIME_ZONE=Asia/Shanghai
    networks:
    - local.net
    stdin_open: true
    tty: true
    volumes:
    - ./data/data:/data

  c_runtime:
    container_name: run.me
    hostname: run.me
    image: run:1.0
    build:
      context: ./run
    environment:
    - TIME_ZONE=Asia/Shanghai
    networks:
    - local.net
    stdin_open: true
    tty: true
    volumes:
    - ./data/data:/data

  c_nginx:
    container_name: nginx.me
    hostname: nginx.me
    image: nginx:latest
    restart: on-failure:5
    ports:
      - "80:80"
    environment:
    - TIME_ZONE=Asia/Shanghai
    networks:
    - local.net
    stdin_open: true
    tty: true
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./data/data:/var/www/html

  c_php:
    container_name: php.me
    hostname: php.me
    build:
      context: ./php
    restart: on-failure:5
    environment:
    - TIME_ZONE=Asia/Shanghai
    networks:
    - local.net
    stdin_open: true
    tty: true
    volumes:
    - ./data/html:/var/www/html

  c_mysql:
    container_name: mysql.me
    hostname: mysql.me
    image: mysql:latest
    restart: on-failure:5
    environment:
    - TIME_ZONE=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=123456
    networks:
    - local.net
    stdin_open: true
    tty: true
    volumes:
    - ./data/mysql:/var/lib/mysql

  c_mongo:
    container_name: mongo.me
    hostname: mongo.me
    image: mongo:latest
    restart: on-failure:5
    environment:
    - TIME_ZONE=Asia/Shanghai
    networks:
    - local.net
    stdin_open: true
    tty: true
    volumes:
    - ./data/mongo:/data/db

  c_redis:
    container_name: redis.me
    hostname: redis.me
    image: redis:latest
    restart: on-failure:5
    environment:
    - TIME_ZONE=Asia/Shanghai
    networks:
    - local.net
    stdin_open: true
    tty: true
    volumes:
    - ./data/redis:/data